### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by ElnuDev** [dlchamp/Code-to-MD#1]
Currently, this project is only published to the official Visual Studio Code marketplace. This makes it unavailable to unofficial forks of VSCode, such as VSCodium, since Microsoft blocks usage of it outside of official builds of VSCode. Could you please also publish to [OpenVSX](https://open-vsx.org/) so it's more accessible? Thanks! This project seems super useful, great work.

**Comment by dlchamp** [comment]
For sure.   I'm going to be honest, I didn't know that existed.

edit:
Looks like I won't be able to do that for now.   Requires an account and registration is closed for the time being.
*"Account registration on our website is temporarily disabled due to spam. We apologize for the inconvenience and are working to restore the functionality as soon as possible."*

As soon as it's available again, I will for sure publish it there as well.  In the mean time, is it possible to manually install via [.vsix file here](https://github.com/dlchamp/Code-to-MD/releases/tag/v0.0.5)?

**Comment by dlchamp** [comment]
Published.  Awaiting ownership verification, but the extension should now be available:
https://open-vsx.org/extension/DLCHAMP/code-to-markdown
